### ISSUE TITLE
Does this package support communicating directly over the local Wi-Fi network

### ISSUE THREAD

**Issue by guyluz11** [LucasChilders/dart_lifx#2]
I am building a smart Hub in dart and I am thinking of adding support for Lifx devices with this package.

For the Hub I prefer to communicate locally with the smart devices, does this package communicate locally with Lifix devices?.

**Comment by LucasChilders** [comment]
Hey, thanks for the interest in the project.

This project only currently supports web requests to the LIFX API, nothing is done locally.

**Comment by guyluz11** [comment]
Ok, thanks.
